# Generated by Django 5.0.1 on 2024-01-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='complement',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
