# Generated by Django 5.0.1 on 2024-01-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_product_variation_delete_produto_delete_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
